// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEyhY6BP9ynxEPX_miKtfDS13Zf2Ril8',
    appId: '1:14547584427:web:192e47e2ca8b1bb015feee',
    messagingSenderId: '14547584427',
    projectId: 'healthlogger-27230',
    authDomain: 'healthlogger-27230.firebaseapp.com',
    storageBucket: 'healthlogger-27230.appspot.com',
    measurementId: 'G-X9HX4PHRXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZndRpCgXgjT6LtrcytK36StozYP8Vbs',
    appId: '1:14547584427:android:8596ac783555b02315feee',
    messagingSenderId: '14547584427',
    projectId: 'healthlogger-27230',
    storageBucket: 'healthlogger-27230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH4wskbarXIuTpSN1_7zP9-XK0iopEYuY',
    appId: '1:14547584427:ios:09b289e95d88210e15feee',
    messagingSenderId: '14547584427',
    projectId: 'healthlogger-27230',
    storageBucket: 'healthlogger-27230.appspot.com',
    iosBundleId: 'com.example.healthlogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH4wskbarXIuTpSN1_7zP9-XK0iopEYuY',
    appId: '1:14547584427:ios:4d9e90e78b1df20d15feee',
    messagingSenderId: '14547584427',
    projectId: 'healthlogger-27230',
    storageBucket: 'healthlogger-27230.appspot.com',
    iosBundleId: 'com.example.healthlogger.RunnerTests',
  );
}
